spring.application.name=api_gateway
server.port=8080

server.frontend.url=http://localhost:5173

jwt.secret=7af60a6cd75548d161f8eb420c0be88e
jwt.expiration=2

# ========================
# Eureka
# ========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.http.codecs.max-in-memory-size=10MB

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.cloud.gateway=TRACE

# ========================
# Gateway routes
# ========================
spring.cloud.gateway.routes[0].id=auth
spring.cloud.gateway.routes[0].uri=lb://AUTH
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=tours
spring.cloud.gateway.routes[1].uri=lb://TOURS
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/tours/**

spring.cloud.gateway.routes[2].id=booking
spring.cloud.gateway.routes[2].uri=lb://BOOKING
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/bookings/**


# ========================
# Google OAuth2 qua API Gateway
# ========================

# OAuth2 login start
# spring.cloud.gateway.routes[3].id=auth-oauth2
# spring.cloud.gateway.routes[3].uri=lb://AUTH
# spring.cloud.gateway.routes[3].predicates[0]=Path=/oauth2/**

# # Google callback
# spring.cloud.gateway.routes[4].id=auth-login-oauth2
# spring.cloud.gateway.routes[4].uri=lb://AUTH
# spring.cloud.gateway.routes[4].predicates[0]=Path=/login/**

spring.cloud.gateway.routes[3].id=google-auth
spring.cloud.gateway.routes[3].uri=lb://AUTH
spring.cloud.gateway.routes[3].predicates[0]=Path=/oauth2/**,/login/**,/error
