spring.application.name=api_gateway
server.port=8080

server.frontend.url = http://localhost:5173

jwt.secret=7af60a6cd75548d161f8eb420c0be88e
jwt.expiration=2

# ========================
# Eureka
# ========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ========================
# Gateway routes
# ========================
spring.cloud.gateway.server.webflux.routes[0].id=auth
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=tours
spring.cloud.gateway.server.webflux.routes[1].uri=lb://TOURS
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/tours/**

spring.cloud.gateway.server.webflux.routes[2].id=booking
spring.cloud.gateway.server.webflux.routes[2].uri=lb://BOOKING
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/booking/**