spring.application.name=tours

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/tours
spring.datasource.username=postgres
spring.datasource.password=01596321
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=7af60a6cd75548d161f8eb420c0be88e
jwt.expiration=2
